http://{default}/:
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
  type: redirect
https://{default}/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: true
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: false
  type: upstream
  upstream: drupal:http
